version: '3.7'

services:
#  main:
#    container_name: main
#    build:
#      context: .
#      target: development
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 3001:3001
#    command: npm run start:api
#    env_file:
#      - .env
#    networks:
#      - webnet
#    depends_on:
#      - redis
#      - postgres
#  react:
#    container_name: react
#    build:
#      context: ./
#      dockerfile: ./apps/web/Dockerfile
#    ports:
#      - 3002:3002
#    environment:
#      - NODE_ENV=development
#    volumes:
#      - ./web:/usr/src/app
#        - /usr/src/app/node_modules
#    stdin_open: true
#    tty: true
#    depends_on:
#      - main

  redis:
    container_name: redis
    image: redis:6.0
    ports:
        - "6379:6379"
    volumes:
        - redis:/data
    networks:
      - webnet
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: NnVvGET
      POSTGRES_USER: postgres
      POSTGRES_DB: gb_news
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  webnet:
volumes:
  pgdata:
  redis:
     driver: local
